### PR TITLE
Update database name to match new db

### PR DESCRIPTION
**Pull request by tofu-rocketry**
For the migration to the centrally managed database, then schema names in this file need updating.

### CODE REVIEW

**Review by Sae126V — APPROVED** [review]
So, the changes are  as follows:

`iris_cloud` -> `apel_iris_cloud` DB
`iris_shared` -> `apel_iris_shared` DB
`iris_grid` ->  `apel_iris_grid` DB


LGTM!

**Comment by Sae126V** [comment]
So, Do we need to update the provisioning/datasources/iris.yml ?

**Comment by tofu-rocketry** [comment]
> So, Do we need to update the provisioning/datasources/iris.yml ?

Quattor fully manages that file in production, but I guess I should make them match. Will push a commit for that.

**Review by Sae126V — APPROVED** [review]
LGTM, Adrian.

**Pull request merged**
