### PR TITLE
Mixed fixes

### LINKED ISSUE #134: Make estimated total usage bar more visible
It's a bit hard to see so tweak transparency to maybe 20% up from 11%

### LINKED ISSUE #136: Check stacking setting
Main chart seems to be null values are null, rather than zero, which is messing up some of the stacking.

### PR DESCRIPTION
**Pull request by tofu-rocketry**
- Resolves #134
- Resolves #136 
- Disables updating of provisioned dashboards from within the UI
- ~~Corrects some SDC naming (not that that's used)~~

### CODE REVIEW

**Comment by gregcorbett** [comment]
I feel slightly uneasy about changing the SeaDataCloud stuff and having it diverge from the documentation they have. I wonder if it needs to stay part of this repository going forward - it exists in a [tagged version](https://github.com/apel/grafana-dashboards/tree/v36) after all.

**Comment by tofu-rocketry** [comment]
> I feel slightly uneasy about changing the SeaDataCloud stuff and having it diverge from the documentation they have. I wonder if it needs to stay part of this repository going forward - it exists in a [tagged version](https://github.com/apel/grafana-dashboards/tree/v36) after all.

Ok, I've removed it.

**Comment by tofu-rocketry** [comment]
Forgot to say, you can see the changes on iris-accounting-preprod (and do a side-by-side comparison with prod).

**Comment by gregcorbett** [comment]
I would make the est. usage even less transparent. Maybe even a solid grey? Might need to change the Diamand colour though...

**Comment by tofu-rocketry** [comment]
Ok, I'll go to 50% transparent, final offer. 🤝 Not a fan of solid as it's not real data, just a projection.

It's up on preprod now.

**Review by gregcorbett — APPROVED** [review]

**Pull request merged**
