### PR TITLE
[GT-142] Adds dropdown to select which line series appear

### LINKED ISSUE #151: Add dropdown (or similar) to select which line series appear?

### PR DESCRIPTION
**Pull request by rowan04**
- adds dropdown with options for both, none, just allocation and just capacity

resolves #151

### CODE REVIEW

**Comment by rowan04** [comment]
needs newline at end of file

**Comment by gregcorbett** [comment]
Is this change running on a Cloud VM somewhere?

**Comment by rowan04** [comment]
> Is this change running on a Cloud VM somewhere?

I doubt it. Don't think so.

**Comment by gregcorbett** [comment]
Maybe you can show of the change at the next dev meeting? It's hard to look at the JSON changes and not just be like, "Yep, that's still JSON".

**Comment by rowan04** [comment]
> Maybe you can show of the change at the next dev meeting? It's hard to look at the JSON changes and not just be like, "Yep, that's still JSON".

ok

**Review by tofu-rocketry — APPROVED** [review]

**Pull request merged**
