### PR TITLE
GT-158 Make estimated total usage more distinct

### LINKED ISSUE #152: Make estimated usage forecast most distinct
Hashed fill probably isn't possible. Gradient, different colour?

### PR DESCRIPTION
**Pull request by rowan04**
- drop down variable added for estimated total usage
- affects the estimated total usage on the main view
- change colour of estimated total usage bar
- add estimated total usage info on guide
- added 2 images

resolves #152

### CODE REVIEW

**Comment by rowan04** [comment]
graph with bar:


graph without bar:


guide:

**Comment by rowan04** [comment]
After review, this feedback was received:
image

Below is the before-mentioned similarity between the proposed colour change to the estimated total usage, CCFE and CCP4.
image

**Review by tofu-rocketry — CHANGES_REQUESTED** [review]
Let's try a transparent version of the light blue and see if that works. If not, we'll go with the other changes and revert the colour to as before.

**Comment by tofu-rocketry** [comment]
#162 is merged now, so there's probably some minor conflicts to fix in this PR.

**Comment by rowan04** [comment]
> Let's try a transparent version of the light blue and see if that works. If not, we'll go with the other changes and revert the colour to as before.

here is the transparent version of the light blue
image

**Comment by tofu-rocketry** [comment]
If you could just rebase this and sort the conflicts please, that would be good.

**Comment by rowan04** [comment]
Committed final change from local repo

**Comment by rowan04** [comment]
rebase to merge commits

**Comment by rowan04** [comment]
fixed conflicts

**Review by tofu-rocketry — APPROVED** [review]

**Pull request merged**
